version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: binhbst1
      POSTGRES_USER: binhbst1
      POSTGRES_PASSWORD: Binh@2003
